### ISSUE TITLE
system interface

### ISSUE THREAD

**Issue by lnbeloate** [surjeets/Animal_Home_Cage#4]
I have loaded and run this repo and the 'Animal_motion_detector' and 'AnimalTracking_TH_V2' files and everything seems to be working fine (thank you for sharing!), however I can't figure out how to get to the web system interface. Do I need to change the settings somewhere or which command determines this? I'm new to this and am following along with your paper, so I apologize if this is obvious.

**Comment by johndoe2309** [comment]
I have the same question for surjeets

**Comment by surjeets** [comment]
> I have loaded and run this repo and the 'Animal_motion_detector' and 'AnimalTracking_TH_V2' files and everything seems to be working fine (thank you for sharing!), however I can't figure out how to get to the web system interface. Do I need to change the settings somewhere or which command determines this? I'm new to this and am following along with your paper, so I apologize if this is obvious.

if you have installed the packages as instructed on a raspberry pi. can you please send a screenshot of http://localhost/var/www/html/index.php

**Comment by surjeets** [comment]
check this for more troubleshooting and details: https://github.com/surjeets/Animal_Home_Cage/issues/3
